# -*- coding: utf-8 -*-
"""capture.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1idFBsd-mNL0am4SwJG4p2DdQjKMIcCU-
"""

# !pip install face_recognition

import sys
import face_recognition
import cv2
import numpy as np
from PIL import ImageFont, ImageDraw, Image
import glob

video_catpture = cv2.VideoCapture(0)

def main():
  while True:
    # ビデオの単一フレームを取得
    _, frame = video_catpture.read()

    # 結果をビデオで表示
    cv2.imshow("Video", frame)

    # ESCキーで終了
    if cv2.waitKey(1) == 27:
      break

main()

video_catpture.release()
cv2.destroyAllWindows()